In [2]:
import pickle
import pandas as pd
import numpy as np

In [8]:
ohe_sex = pickle.load(open('../models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('../models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('../models/clf.pkl', 'rb'))

In [21]:
# Assume user Input
# Pclass / gender / age / sibsp / parch / fare / embarked
test_input = np.array([3, 'female', 23.0, 0, 0, 15.5, 'S'], dtype = object).reshape(1, 7)

In [22]:
test_input

array([[3, 'female', 23.0, 0, 0, 15.5, 'S']], dtype=object)

In [23]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))

C:\Users\Santosh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [24]:
test_input_sex

array([[1., 0.]])

In [25]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1,1))

In [26]:
test_input_embarked

array([[0., 0., 1.]])

In [27]:
test_input_age = test_input[:, 2].reshape(1, 1)

In [28]:
test_input_age

array([[23.0]], dtype=object)

In [29]:
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis = 1)

In [30]:
test_input_transformed.shape

(1, 10)

In [31]:
clf.predict(test_input_transformed)

array([1], dtype=int64)